config/routes.rb
Rails.application.routes.draw do

  # get 'session/new'
  #
  # get 'session/create'
  #
  # get 'session/destroy'

  root 'flights#search' # Routing for home page will show the flights available

  resources :flights do
    member do
      resources :reservations
    end
  end
  resources :airplanes
  resources :users


  get '/login' => 'session#new', :as => 'login'  # sign-in page
  post '/login' => 'session#create' #
  delete '/login' => 'session#destroy' # path to log-out
  get '/admin' => 'pages#new' #path to admin log in
  get '/search' => 'flights#search' # This will be used for backbone
  get '/search_by_query' => 'flights#search_by_query'
  get '/flight/:id' => 'flights#flight'



end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id              :integer          not null, primary key
#  flight_num      :text
#  origin          :text
#  destination     :text
#  flight_datetime :datetime
#  airplane_id     :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Flight < ActiveRecord::Base
  belongs_to :airplane
  has_many :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /search
  def search
    @airplane_seat_column = ( "A".."Z" ).to_a
  end

  # GET /flight/:id
  def flight
  end

  # GET /search_by_query
  def search_by_query
    @flights = Flight.where( :origin => params[ :origin ], :destination => params[ :destination ] )

    respond_to do | format |
      if @flights.count > 0
        format.json { render json: @flights }
        format.html { render :search }
      else
        format.json { render json: { msg: "No data" } }
        format.html { render :search }
      end
    end

  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @airplane_seat_column = ( "A".."Z" ).to_a
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    # Used to check the date and time being set
    flight_datetime_time = Time.new( flight_params[ "flight_datetime(1i)" ].to_i,
                                     flight_params[ "flight_datetime(2i)" ].to_i,
                                     flight_params[ "flight_datetime(3i)" ].to_i,
                                     flight_params[ "flight_datetime(4i)" ].to_i,
                                     flight_params[ "flight_datetime(5i)" ].to_i )


    @airplane = @flight.airplane

    # @row = @airplane.rows
    # @columns = @airplane.columns
    #
    # @number_of_seats = @rows * @columns

    @rows = @airplane.rows
    @columns = @airplane.columns

    @number_of_seats = @rows * @columns

    # @number_of_seats.times do
    #   r = Reservation.create({:flight_id = @flight.id});
    # end
    respond_to do |format|
      # Only if the flight date and time set to greater than current date and time,
      #  then proceed to create flight
      if flight_datetime_time > DateTime.now.to_time
        if @flight.save
          p "I was here just now"
          format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
          format.json { render :show, status: :created, location: @flight }
        end
      else
        flash[ :notice ] = "Date or time should be greater than current date and time"
        format.html { render :new }
        format.json { render json: @flight.errors,
                             status: :unprocessable_entity,
                             :msg => "Date or time should be greater than current date and time" }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    # Used to check the date and time being set
    flight_datetime_time = Time.new( flight_params[ "flight_datetime(1i)" ].to_i,
                                    flight_params[ "flight_datetime(2i)" ].to_i,
                                    flight_params[ "flight_datetime(3i)" ].to_i,
                                    flight_params[ "flight_datetime(4i)" ].to_i,
                                    flight_params[ "flight_datetime(5i)" ].to_i )

    respond_to do |format|
      # Only if it is set to have the time being updated greater than current time,
      #   then can proceed on updating it
      if flight_datetime_time > DateTime.now.to_time
        if @flight.update(flight_params)
          format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
          format.json { render :show, status: :ok, location: @flight }
        end
      else
        flash[ :notice ] = "Date or time should be greater than current date and time"
        format.html { render :edit }
        format.json { render json: @flight.errors,
                             status: :unprocessable_entity,
                             :msg => "Date or time should be greater than current date and time" }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flight_num, :origin, :destination, :flight_datetime, :airplane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if flash[ :notice ] %>
    <div class="notice"><%= flash[ :notice ] %></div>
    <br />
    <% flash[ :notice ] = "" %>
  <% end %>

  <div class="field">
    <%= f.label :flight_num %><br>
    <%= f.text_area :flight_num, :required => true %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_area :origin, :required => true %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_area :destination, :required => true %>
  </div>
  <div class="field">
    <%= f.label :flight_datetime %><br>
    <%= f.datetime_select :flight_datetime, :default => Time.now %>
  </div>
  <div class="field">
    <%= f.label :airplane_id %><br>
    <%= f.collection_select :airplane_id, Airplane.all, :id, :name, { :prompt => "Select a plane" }, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/flight.html.erb
<!-- <h2>Suppose to see the view here</h2>
<h5>Temporarily left as maintenance</h5>
<script type="html/template" id="SearchResultTemplate">
  <%%= flight_num %> | <%%= origin %> - <%%= destination %> | <%%= flight_datetime %> | <%%= airplane_id %>
</script>

 -->

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight num</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Flight datetime</th>
      <th>Airplane</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_num %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.flight_datetime %></td>
        <td><%= flight.airplane_id %></td>
        <td><%= link_to 'Show', flight %></td>
        <% if @current_user.present? && @current_user.isadmin %>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @current_user.present? && @current_user.isadmin %>
  <%= link_to 'New Flight', new_flight_path %><br />
<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/search.html.erb
<button>
  Search your flight!
</button>

<br />


<div class="white_board">
  <div id="flightsearch">
    <h2>Search available flights</h2>
    <div id="searchform"></div>
    <br />
    <div id="searchresult" style="width: 80%; margin: 3px auto;"></div>
  </div>
</div>

<script type="html/template" id="SearchResultHeaderTemplate">
  <table>
    <thead>
      <tr>
        <th>Flight Number</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Date</th>
        <th>Time</th>
        <th>Airplane Name</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</script>

<script type="html/template" id="SearchResultTemplate">
    <td><%%= flight_num %></td>
    <td><%%= origin %></td>
    <td><%%= destination %></td>
    <td><%%= flight_date %></td>
    <td><%%= flight_time %></td>
    <td><%%= airplane_name %></td>
</script>

<script type="html/template" id="SingleSearchResultTemplate">
   <table>
     <thead>
       <tr>
         <th>Flight Number</th>
         <th>Origin</th>
         <th>Destination</th>
         <th>Date</th>
         <th>Time</th>
         <th>Airplane Name</th>
       </tr>
     </thead>
     <tbody>
        <tr>
          <td><%%= flight_num %></td>
          <td><%%= origin %></td>
          <td><%%= destination %></td>
          <td><%%= flight_date %></td>
          <td><%%= flight_time %></td>
          <td><%%= airplane_name %></td>
        </tr>
     </tbody>
  </table>
</script>


<script type="html/template" id="SearchFormTemplate">
  <div>
    <input type="text" id="origin" placeholder="Origin" />

    <input type="text" id="destination" placeholder="Destination" />
    <button class="filter_button">Filter</button>
  </div>
</script>

<script type="html/template" id="FlightReservationTemplate">
  <h2>Select Your Seat</h2>

</script>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight num:</strong>
  <%= @flight.flight_num %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Flight datetime:</strong>
  <%= @flight.flight_datetime %>
</p>

<p>
  <strong>Airplane:</strong>
  <%= @flight.airplane.name %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

<div id="app">
  <h1>This is where Backbone should be loaded</h1>
</div>

<script type="html/template" id="AppViewTemplate">
  <h1>Our Secrets App</h1>
  <div id="secretForm">
    An instance of the SecretInputView should be loaded here
  </div>
  <ul id="secrets">
    <!--
      Many instances of the SecretView should be loaded here -->
  </ul>
</script>

<script type="html/template" id="SecretInputViewTemplate">
  <textarea placeholder="Tell me all of your secrets"></textarea>
  <button>Submit</button>
</script>