config/routes.rb
Rails.application.routes.draw do

  # get 'session/new'
  #
  # get 'session/create'
  #
  # get 'session/destroy'

  root 'flights#search' # Routing for home page will show the flights available

  resources :flights do
    member do
      resources :reservations
    end
  end
  resources :airplanes
  resources :users


  get '/login' => 'session#new', :as => 'login'  # sign-in page
  post '/login' => 'session#create' #
  delete '/login' => 'session#destroy' # path to log-out
  get '/admin' => 'pages#new' #path to admin log in
  get '/search' => 'flights#search' # This will be used for backbone
  get '/search_by_query' => 'flights#search_by_query'
  get '/flight/:id' => 'flights#flight'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Burning Airlines</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Cantarell|Lato|Oswald|Roboto" rel="stylesheet">
  <!-- <link href="https://fonts.googleapis.com/css?family=Cantarell|Lato|Roboto" rel="stylesheet"> -->
</head>
<body>

  <nav>
    <ul>
      <li class="logo">
        <%= link_to "Burning airlines", search_path %>
      </li>
      <li class="nav_right">
        <%= link_to "Get me out of here", "https://youtu.be/XDnL8IQYI0o?t=7" %>
      </li>
      <% unless @current_user.present? %>
        <li class="nav_right">
          <%= link_to "Sign Up", new_user_path %>
        </li>
        <li class="nav_right">
          <%= link_to "Login", login_path %>
        </li>
      <% else %>
        <li>
          <%= link_to "Flights", flights_path %>
        </li>
        <% if @current_user.isadmin %>
        <li>
          <%= link_to "Airplanes", airplanes_path %>
        </li>
        <% end %>
        <li class="nav_right">
        <!-- <%#= link_to "Edit Profile", edit_user_path( @current_user.id ) %> | -->
        <%= link_to "Logout #{@current_user.email}", login_path, :method => :delete %>
        </li>
      <% end %>
    </ul>

    <!-- <%# if @current_user.present? %>
      <span>
        You are logged in as <%#= @current_user.email %>
      </span>
    <%# end %> -->
  </nav>

  <header class="wrapper">
    <section class="content">
      <h1>Burning SEATS!</h1>
    </section>
  </header>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>